# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/yobit_defi_view_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(669, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.log_tedit = QtWidgets.QTextEdit(self.groupBox)
        self.log_tedit.setReadOnly(True)
        self.log_tedit.setObjectName("log_tedit")
        self.verticalLayout_3.addWidget(self.log_tedit)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.pair_cmbox = QtWidgets.QComboBox(self.groupBox_2)
        self.pair_cmbox.setMinimumSize(QtCore.QSize(120, 0))
        self.pair_cmbox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pair_cmbox.setObjectName("pair_cmbox")
        self.horizontalLayout_2.addWidget(self.pair_cmbox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.arbitrage_ledit = QtWidgets.QLineEdit(self.groupBox_2)
        self.arbitrage_ledit.setMinimumSize(QtCore.QSize(120, 0))
        self.arbitrage_ledit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.arbitrage_ledit.setObjectName("arbitrage_ledit")
        self.horizontalLayout_3.addWidget(self.arbitrage_ledit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.working_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.working_btn.setObjectName("working_btn")
        self.verticalLayout_4.addWidget(self.working_btn)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.yobit_buy_lbl = QtWidgets.QLabel(self.groupBox_3)
        self.yobit_buy_lbl.setObjectName("yobit_buy_lbl")
        self.horizontalLayout_8.addWidget(self.yobit_buy_lbl)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.yobit_sell_lbl = QtWidgets.QLabel(self.groupBox_3)
        self.yobit_sell_lbl.setObjectName("yobit_sell_lbl")
        self.horizontalLayout_7.addWidget(self.yobit_sell_lbl)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.binance_buy_lbl = QtWidgets.QLabel(self.groupBox_3)
        self.binance_buy_lbl.setObjectName("binance_buy_lbl")
        self.horizontalLayout_6.addWidget(self.binance_buy_lbl)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.binance_sell_lbl = QtWidgets.QLabel(self.groupBox_3)
        self.binance_sell_lbl.setObjectName("binance_sell_lbl")
        self.horizontalLayout_5.addWidget(self.binance_sell_lbl)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.yobit_buy_arbitrage_lbl = QtWidgets.QLabel(self.groupBox_3)
        self.yobit_buy_arbitrage_lbl.setObjectName("yobit_buy_arbitrage_lbl")
        self.horizontalLayout_4.addWidget(self.yobit_buy_arbitrage_lbl)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.binance_buy_arbitrage_lbl = QtWidgets.QLabel(self.groupBox_3)
        self.binance_buy_arbitrage_lbl.setObjectName("binance_buy_arbitrage_lbl")
        self.horizontalLayout_4.addWidget(self.binance_buy_arbitrage_lbl)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 669, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "yobit_defi"))
        self.groupBox.setTitle(_translate("MainWindow", "Лог"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Настройки"))
        self.label.setText(_translate("MainWindow", "Пара"))
        self.label_2.setText(_translate("MainWindow", "% арбитража"))
        self.working_btn.setText(_translate("MainWindow", "Старт"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Данные"))
        self.label_6.setText(_translate("MainWindow", "Цена покупи на yobit"))
        self.yobit_buy_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "Цена продажи на yobit"))
        self.yobit_sell_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Цена покупки на binance"))
        self.binance_buy_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "Цена продажи на binance"))
        self.binance_sell_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "Процент арбитража при "))
        self.label_4.setText(_translate("MainWindow", "покупки на yobit"))
        self.yobit_buy_arbitrage_lbl.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "покупки на binance"))
        self.binance_buy_arbitrage_lbl.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

